### PR TITLE
fix rviz configs for new namespaces

### PR DESCRIPTION
**Pull request by floweisshardt**

### CODE REVIEW

**Comment by mgruhler** [comment]
This breaks rviz configs for all cob3 and r@w.
Will not merge it.

We need to create robot specific rviz configs.

**Comment by floweisshardt** [comment]
@ipa-mig: you're right. to avoid having separated rviz configs we could just configure 4 scanners (front, left, right, rear). Would that be OK for you?

**Comment by mgruhler** [comment]
well, then we would need to configure 5 (top), or maybe even six, if we add additional ones. I'm think this is not very nice.

Maybe we can have one config for cob4, one for cob3 and one for raw3?
I'm guessing, they are (more or less) similar...

**Comment by fmessmer** [comment]
not yet resolved...what's the procedure going to be?

**Comment by benmaidel** [comment]
still conflicts to merge @ipa-fmw

**Comment by floweisshardt** [comment]
conflicts might be resolved, but it is still open how to solve @ipa-mig's comment https://github.com/ipa320/cob_navigation/pull/62#issuecomment-171306159

**Comment by mgruhler** [comment]
I'm closing this one now.
Anyone with a good concept please let me know.

**Pull request closed without merging**
