### PR TITLE
remove obsolete configs due to unsupported robots

### PR DESCRIPTION
**Pull request by fmessmer**
related to https://github.com/ipa320/cob_robots/pull/588

### CODE REVIEW

**Comment by fmessmer** [comment]
Tag has been added: https://github.com/ipa320/cob_navigation/tree/eol-cob3

**Review by floweisshardt — APPROVED** [review]

**Review by mgruhler — APPROVED** [review]
In principle approved. However:

@ipa-bnm what does the MIT do with r@w3-6?
@ipa-srd should we keep r@w3-4 for BMW
@ipa-svn what about r@w3-2 in Lund?
[Distribution](http://wiki.ros.org/Robots/Care-O-bot/distribution)

@ipa-fxm @ipa-fmw Should we also update the following ROS wiki pages accordingly? Should we keep all robots there and mark them as **not-supported** or **deprecated**?

- http://wiki.ros.org/Robots/Care-O-bot
- http://wiki.ros.org/Robots/Care-O-bot/distribution

**Comment by floweisshardt** [comment]
I'd like to keep them listed and mark them as unsupported with ROS versions `>` (or `>=` ) indigo

**Comment by stefandoerr** [comment]
I haven't heard anything from BMW for a while. I assume that nobody works with their r@w anymore, at least at the moment.

**Comment by mgruhler** [comment]
@ipa-srd so I vote for removing it for now.

@ipa-fmw please doublecheck http://wiki.ros.org/Robots/Care-O-bot/distribution, http://wiki.ros.org/Robots/Care-O-bot and http://wiki.ros.org/Robots/cob3
Releveant PRs https://github.com/ipa320/cob_robots/pull/253, https://github.com/ipa320/cob_robots/pull/237 and https://github.com/ipa320/cob_robots/pull/588

**Comment by fmessmer** [comment]
Decision is: removing them!
As soon as any other robot actually wants an update, we will decide on re-adding them...

**Pull request merged**
