### PR TITLE
enable roslaunch checks (again)

### PR DESCRIPTION
**Pull request by floweisshardt**
requires https://github.com/ros/ros_comm/pull/814 to be merged and released (or an overlay of ros_comm)

### CODE REVIEW

**Comment by mgruhler** [comment]
CR: ok, but please do not merge yet.

@ipa-fwm will new debian packages be released for indigo? If not, I'd rather not merge this to indigo to avoid requiring the respective overlay. We should then rather go for the kinetic branches, once they are prepared.

**Comment by floweisshardt** [comment]
I truly hope that there will be another release of ros_comm/indigo-devel soon. 

And yes, we should wait with merging until the release is done and in the public repo.

**Comment by floweisshardt** [comment]
the new release of ros_comm is public now, I'll retrigger travis to see if it works

**Comment by floweisshardt** [comment]
Travis is happy, so we can merge this. 

@ipa-mig: please merge

**Comment by mgruhler** [comment]
Yay :tada:

**Pull request merged**
